### ISSUE TITLE
Can't pull from private repo

### ISSUE THREAD

**Issue by revxx14** [zaggino/brackets-git#973] opened 2015-03-24 17:51 UTC
Because I can't enter a username/password in the clone dialog, I'm unable to clone from a private repo. I have to switch it to public, then clone it, then switch it back to private, then set up the username/password in the push interface.

It'd be great if you could add a log in interface in to the clone dialog, but in the mean time, is there a workaround I could do?

**Comment by zaggino** [comment] 2015-03-24 21:46
You could try using url with username and password for now `https://zaggino:mypassword@github.com/zaggino/brackets-git.git` or just clone in terminal.

Closing as a duplicate of #707

**Closed by zaggino** 2015-03-24 21:46 UTC
