### ISSUE TITLE
Max connection attempts reached when connecting to NodeJS

### ISSUE THREAD

**Issue by belmarca** [zaggino/brackets-git#410] opened 2014-04-15 04:47 UTC
[Please describe your problem here]

--------------------------------

*Brackets 0.38.0-12606 (mac) & Brackets-Git 0.13.2*

**Failed to connect to NodeJS. If you just updated the extension close all instances of Brackets and try starting again.**

```
Error: Max connection attempts reached
```

```
Error: Max connection attempts reached
    at Object.exports.toError (file:///Users/chm/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:144:16)
    at Object.<anonymous> (file:///Users/chm/Library/Application%20Support/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:61:37)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:550:26676)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:550:27489)
    at Object.<anonymous> (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:550:28170)
    at j (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:550:26676)
    at Object.k.fireWith (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:550:27489)
    at Object.e.(anonymous function) [as reject] (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:550:28469)
    at Object.eval (/utils/NodeConnection.js:308:34)
    at Object.<anonymous> (file:///Applications/Brackets.app/Contents/www/thirdparty/thirdparty.min.js:550:28045)
```

**Comment by pietrondo** [comment] 2015-01-03 09:39
Same problem with the last version of bracket (I use archlinux)
![selezione_011](https://cloud.githubusercontent.com/assets/6080662/5602069/d54d35fe-9334-11e4-8687-8b28932cd5d6.png)

**Comment by marcoemrich** [comment] 2015-01-07 15:38
I have the same problem on Mint Linux after upgrading to Brackets 1.1. It disappears when I downgrade to 1.0. Maybe it actually is a plugin conflict. I will investigate it further and report back.

**Comment by marcoemrich** [comment] 2015-01-07 15:39
Reload without extensions also removes the error.

**Comment by zaggino** [comment] 2015-01-07 20:04
Probably one of the extensions is not compatible with 1.1, do you have any errors in the console (f12) ?

**Comment by marcoemrich** [comment] 2015-01-07 22:20
Actually, there are a lot errors and warnings:

Download the React DevTools for a better development experience: http://fb.me/react-devtools /thirdparty/react.js:4356
Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:120:32)
    at file:///home/memrich/.config/Brackets/extensions/user/brackets-livescript/main.js:8:7
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/brackets-livescript/main.js:253:7) /utils/DeprecationWarning.js:88
Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:120:32)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/brackets-livescript/main.js:255:5) /utils/DeprecationWarning.js:88
Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at loadOutline (file:///home/memrich/.config/Brackets/extensions/user/crabcode.outline/main.js:260:28)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/crabcode.outline/main.js:398:9)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Registering for deprecated event 'workingSetAdd'. Instead, use MainViewManager.workingSetAdd. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at loadOutline (file:///home/memrich/.config/Brackets/extensions/user/crabcode.outline/main.js:262:28)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/crabcode.outline/main.js:398:9)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Registering for deprecated event 'workingSetRemove'. Instead, use MainViewManager.workingSetRemove. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at loadOutline (file:///home/memrich/.config/Brackets/extensions/user/crabcode.outline/main.js:263:28)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/crabcode.outline/main.js:398:9)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Registering for deprecated event 'workingSetAdd'. Instead, use MainViewManager.workingSetAdd. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/drewkoch.icons/main.js:190:21)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Registering for deprecated event 'workingSetAddList'. Instead, use MainViewManager.workingSetAddList. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/drewkoch.icons/main.js:190:21)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Registering for deprecated event 'workingSetRemove'. Instead, use MainViewManager.workingSetRemove. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/drewkoch.icons/main.js:190:21)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Registering for deprecated event 'workingSetRemoveList'. Instead, use MainViewManager.workingSetRemoveList. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/drewkoch.icons/main.js:190:21)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
Registering for deprecated event 'workingSetSort'. Instead, use MainViewManager.workingSetSort. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/drewkoch.icons/main.js:190:21)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) /utils/EventDispatcher.js:100
getPreferenceStorage is called with client ID 'extensions.brackets-filetreesync,' use PreferencesManager.definePreference instead.
    at Object.getPreferenceStorage (/preferences/PreferencesManager.js:126:32)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/filetreesync/main.js:18:40) /utils/DeprecationWarning.js:88
getValue is called to get preference 'enabled,' use PreferencesManager.get instead.
    at PreferenceStorage.getValue (/preferences/PreferenceStorage.js:128:28)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/filetreesync/main.js:19:29) /utils/DeprecationWarning.js:88
setValue is called to set preference 'enabled,' use PreferencesManager.set instead.
    at PreferenceStorage.setValue (/preferences/PreferenceStorage.js:115:28)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/filetreesync/main.js:38:15) /utils/DeprecationWarning.js:88
Cannot assign Ctrl-R to javascript.renameIdentifier. It is already assigned to javascript.renameIdentifier /command/KeyBindingManager.js:730
Cannot assign Ctrl-Alt-G to catanghel.searchwithgoogle. It is already assigned to catanghel.searchwithgoogle main.js:182
Cannot assign Ctrl-Alt-W to catanghel.searchwithgoogle.stackoverflow. It is already assigned to catanghel.searchwithgoogle.stackoverflow main.js:182
Cannot assign Ctrl-Alt-H to catanghel.searchwithgoogle.phpnet. It is already assigned to view.hideSidebar main.js:182
Cannot assign Ctrl-Alt-H to catanghel.searchwithgoogle.phpnet. It is already assigned to view.hideSidebar main.js:182
Cannot assign Ctrl-Alt-M to catanghel.searchwithgoogle.mdn. It is already assigned to catanghel.searchwithgoogle.mdn main.js:182
Use WorkspaceManager.createBottomPanel() instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/brackets-integrated-development/results-panel.js:15:26) main.js:175
Use brackets.getModule("thirdparty/CodeMirror2/lib/codemirror") instead of global CodeMirror.
    at Object.defineProperty.get (/brackets.js:120:32)
    at file:///home/memrich/.config/Brackets/extensions/user/websiteduck.wdminimap/runmode.js:2:1 main.js:175
getPreferenceStorage is called with client ID 'websiteduck.wdminimap,' use PreferencesManager.definePreference instead.
    at Object.getPreferenceStorage (/preferences/PreferencesManager.js:126:32)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/websiteduck.wdminimap/MinimapMenus.js:31:39) main.js:175
Use MainViewManager.getViews() instead of DocumentManager.getWorkingSet()
    at Object.getWorkingSet (/document/DocumentManager.js:160:28)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/websiteduck.wdminimap/main.js:309:22) main.js:175
getPreferenceStorage is called with client ID 'bracketsTerminal.settings,' use PreferencesManager.definePreference instead.
    at Object.getPreferenceStorage (/preferences/PreferencesManager.js:126:32)
    at _init (file:///home/memrich/.config/Brackets/extensions/user/brackets-terminal/src/settings.js:20:38)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/brackets-terminal/src/settings.js:53:5) main.js:175
Use WorkspaceManager.createBottomPanel() instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at _createPanel (file:///home/memrich/.config/Brackets/extensions/user/brackets-terminal/src/panel.js:19:37)
    at Object.init (file:///home/memrich/.config/Brackets/extensions/user/brackets-terminal/src/panel.js:83:13)
    at file:///home/memrich/.config/Brackets/extensions/user/brackets-terminal/main.js:109:15
    at _callHandler (/utils/AppInit.js:93:13)
    at _addListener (/utils/AppInit.js:128:13)
    at Object.htmlReady (/utils/AppInit.js:150:9)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/brackets-terminal/main.js:98:13) main.js:175
Failed to load resource file:///opt/brackets/www/img/glyphicons-halflings.png
Use WorkspaceManager.createBottomPanel() instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at InfoPanel.init (file:///home/memrich/.config/Brackets/extensions/user/aivanov.command-line-shortcuts/InfoPanel.js:17:31)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/aivanov.command-line-shortcuts/main.js:16:9) main.js:175
Cannot assign Ctrl-Shift-B to extension.commandline.run.0. It is already assigned to cmd.skipCurrentMatch main.js:182
[theseus] fsm: -> waitingForApp main.js:168
Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at new TernReferences (file:///home/memrich/.config/Brackets/extensions/user/ternific/TernReferences.js:30:14)
    at new TernManager (file:///home/memrich/.config/Brackets/extensions/user/ternific/TernManager.js:34:31)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/ternific/main.js:27:23)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///opt/brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///opt/brackets/www/thirdparty/requirejs/require.js:57:31) main.js:175
Failed to load resource: the server responded with a status of 414 (Request-URI Too Long) http://brackets-online.herokuapp.com/tick/53d5549ee31c428fe600006f/%3C!DOCT… browser does not support javascript.        </noscript>    </body></html>
Can't track online status, retry in 5 mins main.js:168
Cannot assign Ctrl-Alt-/ to redmunds.show-shortcuts.view.shortcuts. It is already assigned to pflynn.searchCommands main.js:182
NodeSocketTransport - start main.js:168
Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at file:///home/memrich/.config/Brackets/extensions/user/filetreesync/main.js:41:24
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:290:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28045)
    at Object.eval (/brackets.js:288:30)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860) main.js:175
AppInit main.js:168
000false main.js:168
Use WorkspaceManager.createBottomPanel() instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at file:///home/memrich/.config/Brackets/extensions/user/brackets-emmet/prompt.js:52:24
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:290:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28045)
    at Object.eval (/brackets.js:288:30) main.js:175
[theseus] fsm: -> disconnected main.js:168
Registering for deprecated event 'currentDocumentChange'. Instead, use MainViewManager.currentFileChange. Error
    at Object.on (/utils/EventDispatcher.js:100:43)
    at registerListeners (file:///home/memrich/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:372:5)
    at file:///home/memrich/.config/Brackets/extensions/user/mikaeljorhult.brackets-todo/main.js:511:3
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:290:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28045)
    at Object.eval (/brackets.js:288:30) main.js:175
Use WorkspaceManager.createBottomPanel() instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at Object.init (file:///home/memrich/.config/Brackets/extensions/user/theseus/src/Panel.js:79:33)
    at _init (file:///home/memrich/.config/Brackets/extensions/user/theseus/main.js:319:15)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:290:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28045) main.js:175
Use WorkspaceManager.createBottomPanel() instead of PanelManager.createBottomPanel().
    at Object.exports.createBottomPanel (/view/PanelManager.js:53:28)
    at Object.init (file:///home/memrich/.config/Brackets/extensions/user/theseus/src/EpochPanel.js:226:30)
    at _init (file:///home/memrich/.config/Brackets/extensions/user/theseus/main.js:320:20)
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:290:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28045) main.js:175
Cannot assign Ctrl-Alt-B to io.emmet.balance_outward. It is already assigned to builder.build main.js:182
Cannot assign Ctrl-Shift-J to io.emmet.split_join_tag. It is already assigned to pflynn.evalinbrowser main.js:182
Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp main.js:182
Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown main.js:182
 main.js:110
These files were using Brackets' NodeConnection:
 main.js:168
[node-error 11:11:28 PM] [Launcher] uncaught exception at top level, exiting. Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13) main.js:182
[node-info 11:11:28 PM] [Server] stopping NodeDebugUtils.js:114
File watchers went offline! main.js:175
[brackets-git] Error
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) main.js:182
[brackets-git] Error
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) main.js:182
[brackets-git] Error
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) main.js:182
 main.js:110
These files were using Brackets' NodeConnection:
 main.js:168
Possibly unhandled Error: Max connection attempts reached
    at Object.exports.toError (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/ErrorHandler.js:162:19)
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:67:37)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28354)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.fireWith (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27673)
    at Object.e.(anonymous function) [as reject] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28653)
    at Object.eval (/utils/NodeConnection.js:320:34)
    at Object.<anonymous> (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28229) main.js:182
Possibly unhandled Error
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) main.js:182
Possibly unhandled Error
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) main.js:182
Possibly unhandled Error
    at Object.<anonymous> (file:///home/memrich/.config/Brackets/extensions/user/zaggino.brackets-git/src/ExpectedError.js:11:31)
    at Object.context.execCb (file:///opt/brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///opt/brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.Module.enable (file:///opt/brackets/www/thirdparty/requirejs/require.js:1151:22)
    at Object.Module.init (file:///opt/brackets/www/thirdparty/requirejs/require.js:782:26)
    at callGetModule (file:///opt/brackets/www/thirdparty/requirejs/require.js:1178:63)
    at Object.context.completeLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1552:21)
    at HTMLScriptElement.context.onScriptLoad (file:///opt/brackets/www/thirdparty/requirejs/require.js:1679:29) main.js:182
Watching disabled for /home/memrich/Sync/work/konferenzen_und_talks/2015/OOP2015/livescript_presentation/ main.js:175
Use MainViewManager.getViews() instead of DocumentManager.getWorkingSet()
    at Object.getWorkingSet (/document/DocumentManager.js:160:28)
    at file:///home/memrich/.config/Brackets/extensions/user/martypenner.autosave-files-on-window-blur/main.js:75:39
    at n.event.dispatch (file:///opt/brackets/www/thirdparty/thirdparty.min.js:560:6404)
    at r.handle (file:///opt/brackets/www/thirdparty/thirdparty.min.js:560:3179) main.js:175
[Theseus] Timed out while trying to connect to node main.js:182
GET http://brackets-online.herokuapp.com/tick/53d5549ee31c428fe600006f/%3C!DOCT…%20%20%20%20%3C/head%3E%20%20%20%20%3Cbody%20style=%22background-color:%20 414 (Request-URI Too Long) thirdparty.min.js:561
Can't track online status, retry in 5 mins

**Comment by zaggino** [comment] 2015-01-07 22:31
The problem part is this:
```
[node-error 11:11:28 PM] [Launcher] uncaught exception at top level, exiting. Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13) main.js:182
[node-info 11:11:28 PM] [Server] stopping NodeDebugUtils.js:114
File watchers went offline! main.js:175
```
But I'm not sure why EADDRINUSE pops up.

**Comment by marcoemrich** [comment] 2015-01-07 23:12
It still fails, even with only brackets-git loaded. Then again - it seems
like the complete extension-system is messed up now (can no longer install
and remove extension via the gui). So it's very like the bug is somewhere
else. I will try a clean installation...

**Comment by marcoemrich** [comment] 2015-01-08 04:28
I think I have the brackets core issue https://github.com/adobe/brackets/issues/9625

**Comment by ldiaz** [comment] 2015-04-23 17:33
Hi, I found something usefull, maybe, I got with this same error, and my problem is that the extension bracket-sass is broken since version 2. I get the all the "symptoms" described in this thread and it's not the brackets-git extension mistake but the sass extension one. 

https://github.com/jasonsanjose/brackets-sass/issues/106

I just deleted manually that sass extension and the git extension is working fine again.

**Comment by anukanth** [comment] 2015-05-13 23:45
NodeJs process is trying to connect to you system. It could not connect because the host file might have been modified when you  installed some software. Brackets does not modify this file. It is not an issue with brackets or its installation process.  So even if  you delete all relevant folders, Windows registry and reinstall brackets, the problem is not going to get solved as any of these processes would not modify the host file. You have to manually edit C:/windows/system32/drivers/etc/host with notepad and enter a line without any comment sign (#) and enter the following line without any add on like comma or anything.
127.0.0.1   localhost

Save this file without any extension like txt. Restart brackets.  This file may have other lines. Do not modify any of the other lines.

**Comment by zaggino** [comment] 2016-09-09 05:46
This is fixed in https://github.com/zaggino/brackets-electron/releases

**Closed by zaggino** 2016-09-09 05:46 UTC
Labels: wontfix
